### ISSUE TITLE
Git tag 1.5.0 & 1.6.0

### ISSUE THREAD

**Issue by JensRantil** [lkesteloot/JavaBeanstalkClient#3]
I notice that `pom.xml` version (in `master` branch) is set to `1.4.8-SNAPSHOT`, while there exists both git tag 1.5.0 and 1.6.0.

Question: Has the version in `pom.xml` not been updated accordingly? Or are the git tags incorrect?

**Comment by lkesteloot** [comment]
I don't see tags 1.5.0 and 1.6.0 in the git repo. The most recent tag is 1.4.6, and the pom has 1.4.8 (?). So they're mismatched, but in the opposite way that you say.

**Comment by lkesteloot** [comment]
I'm going to close this, let me know if I misunderstood what you meant by the 1.5.0 and 1.6.0 tags.
