### ISSUE TITLE
Duplicate git tags?

### ISSUE THREAD

**Issue by JensRantil** [lkesteloot/JavaBeanstalkClient#4]
This git repository both has git tag `BeanstalkClient-1.4.6` and `1.4.6`. They point to different commits/`SHA-1`s. Which is authoritative? Could anyone of them be removed?

**Comment by lkesteloot** [comment]
These tags were created before I forked the repo, so I don't know why they're both there. You can't easily remove a tag from git, so I would just leave them. Also I would ignore the "BeanstalkClient-1.4.6" since its format is different than the other tags, which are just the number.

**Comment by JensRantil** [comment]
Late reply here; Removing git tags is pretty easy: https://nathanhoad.net/how-to-delete-a-remote-git-tag
