### ISSUE TITLE
Missing git tags

### ISSUE THREAD

**Issue by JensRantil** [lkesteloot/JavaBeanstalkClient#5]
Based on https://github.com/lkesteloot/JavaBeanstalkClient/commit/1b9c6ff52902e0dbde63d58cbcaf2e20c1b70e9f#diff-600376dffeb79835ede4a0b285078036L5, it looks like there's both been a 1.4.7 and 1.4.8(?) release. However, I can't find git tags for those.

**Comment by lkesteloot** [comment]
Yeah I guess the people I forked from forgot to tag. I don't know what git version they should be referring to. In any case I should make a new version (1.5.0) and tag that.

**Comment by lkesteloot** [comment]
I'll fix this when I release 1.5.0.
