### ISSUE TITLE
Socket timeouts not set

### ISSUE THREAD

**Issue by JensRantil** [lkesteloot/JavaBeanstalkClient#7]
I notice that the `ProtocolHandler` doesn't set any timeout. Two proposals:
- Set a default timeout. That's best practises.
- Allow setting a custom timeout
  - Support injecting a `Socket` into `ProtocolHandler`.
  - Support for injecting `ProtocolHandler` into `BeanstalkClientImpl`. This would allow setting a custom timeout.

What do you think of this? I could submit a pull request if you want.

**Comment by lkesteloot** [comment]
Can you review the change? I just used a simple 30-second timeout. Let me know if you have a current need for something more flexible.
